apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ryfp6j1s1-go
  janus-idp.io/tekton: ryfp6j1s1-go
  backstage.io/kubernetes-id: ryfp6j1s1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ryfp6j1s1-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
